#ifndef GUARD_CONSTANTS_BG_MUSIC_H
#define GUARD_CONSTANTS_BG_MUSIC_H

#define MUS_TITLE 1
// 2 - Empty
#define MUS_TABLE_SELECT 3
// 4 - Empty
#define MUS_UNKNOWN_SONG_1 5
#define MUS_UNKNOWN_SONG_5 6
// 7 - Empty
#define MUS_OPENING 8
#define MUS_HI_SCORE 9
// 10 - Empty
#define MUS_SHOP 11
#define MUS_GAME_OVER 12
#define MUS_END_OF_BALL 13
#define MUS_GO_TO_BONUS_1 14
#define MUS_GO_TO_BONUS_2 15
#define MUS_MOVE_MODE_START 16
#define MUS_GOT_ONE 17
#define MUS_GOT_ONE_2 18 // Duplicate
#define MUS_END_OF_BALL_2 19 // Duplicate
#define MUS_GOT_ITEM 20
#define MUS_CATCH_MODE 21
#define MUS_BREAKING_EGG 22
#define MUS_EVOLUTION 26
#define MUS_RED_TABLE 28
#define MUS_GET_MODE_RED_TABLE 29
#define MUS_EVO_MODE 30
#define MUS_BLUE_TABLE 32
#define MUS_GET_MODE_BLUE_TABLE 33
#define MUS_GARDEN_BONUS_STAGE 36
#define MUS_GRAVE_YARD_BONUS_STAGE 37
#define MUS_LAVA_CAVE_BONUS_STAGE 40
#define MUS_DARK_WATER_BONUS_STAGE 41
#define MUS_IN_THE_SKY_BONUS_STAGE 42
#define MUS_POKEDEX 46
#define MUS_AFTER_THE_BATTLE_BLUE_TABLE 92

#endif // GUARD_CONSTANTS_BG_MUSIC_H
